// Generated by https://quicktype.io

export interface LoginData {
    email: string,
    password: string
}

export interface RegisterData {
    name: string, 
    phone: string, 
    email: string, 
    password: string,
    role: string
}

export interface LoginResponse {
    user:         User;
    access_token: string;
    token_type:   string;
}

export interface ComentarioResponse {
    message: string;
}

export interface PedidoResponse {
    message: string;
}

export interface User {
    id:                number;
    name:              string;
    email:             string;
    email_verified_at: null;
    role:              string;
    phone:             string;
    avatar:            string;
    created_at:        string;
    updated_at:        string;
}

export interface Comentario {
    id_usuario: string,
    comentario: string
}

export interface PedidoData {
    id_usuario: string,
    id_delivery: string,
    payment_method_id: string,
    distance: string,
    address: string,
    status: string,
}
